In [12]:
#From Krish Naik
import pandas as pd
import numpy as np

df=pd.read_csv("DATA_STORAGE/loan_small.csv")
print(df) #this df is called as a dataframe. After reading data it gets converted to a data frame 


#what is max income
df['ApplicantIncome'].max()


#what is average loanamount
df['LoanAmount'].mean()


#lets fill null values.
df.fillna(0)

     Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002     NaN           5849.0                0.0         NaN  urban   
1   LP001003    Male           4583.0                NaN       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0    NaN   
3   LP001006  Female           2583.0             2358.0       120.0   semi   
4   LP001008    Male              NaN                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         NaN  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             18

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002       0           5849.0                0.0         0.0  urban   
1   LP001003    Male           4583.0                0.0       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0      0   
3   LP001006  Female           2583.0             2358.0       120.0   semi   
4   LP001008    Male              0.0                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         0.0  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             1840.0       109.0  urban   
12  LP001028  Female              0.0             8106.0         0.0  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
0            Y  
1            N  
2            Y  
3            0  
4            Y  
5            Y  
6            Y  
7            N  
8            Y  
9            N  
10           Y  
11           Y  
12           Y  
13           N  
14           Y  
15           Y

In [14]:
#creating a dataframe/data arranged in proper format
b=np.arange(0,20).reshape(5,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [17]:
#converting this data into a dataframe
df=pd.DataFrame(data=b,
             index=["R1","R2","R3","R4","R5"],
             columns=["C1","C2","C3","C4"])

In [18]:
df.head() #first 5 records

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [21]:
df.tail() #last 5 records

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [23]:
type(df) #-> this shows dataframe. So it is also a type of data

pandas.core.frame.DataFrame

In [25]:
df.info() #-> gives datatypes of each dataframe

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, R1 to R5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int32
 1   C2      5 non-null      int32
 2   C3      5 non-null      int32
 3   C4      5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [26]:
df.describe()

C1         C2         C3         C4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
#indexing 
#using column name, row index(loc), Index numbers of columns and rows(iloc)

In [29]:
df.head()



C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [33]:
#by column name accessing only these particular columns 
print(df[['C1','C2','C3']]) #since we need multiple columns so nested lists
print()
#getting a single column
print(df['C1'])

    C1  C2  C3
R1   0   1   2
R2   4   5   6
R3   8   9  10
R4  12  13  14
R5  16  17  18

R1     0
R2     4
R3     8
R4    12
R5    16
Name: C1, dtype: int32


In [ ]:
#pandas vs series
"""
pandas(DATAFRAME)->combination of rows and columns 
series->single row or single column
"""


In [42]:
#Loc->use row index name
print(df.loc[['R1', 'R2']])  


    C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7


In [56]:
#Iloc->uses row index and column index
df.head()
df.iloc[2:4,0:2]   #2:4->rows index are from 0 so 0 1 2 so 3rd row se 5th row ke give first and second column


C1  C2
R3   8   9
R4  12  13

In [55]:
df.iloc[2:5,1:4]

#we can also do
df.iloc[2:,1:]

C2  C3  C4
R3   9  10  11
R4  13  14  15
R5  17  18  19

In [63]:
#we want 0 4 8 12 16 and 3 7 11 15 19
df.iloc[0:,0]

R1     0
R2     4
R3     8
R4    12
R5    16
Name: C1, dtype: int32

In [65]:
df.iloc[0:,3] #all rows and fourth column

R1     3
R2     7
R3    11
R4    15
R5    19
Name: C4, dtype: int32

In [68]:
#to convert dataframe into array
df.iloc[:,1:].values  #.values converts to arrays


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [70]:
#basic operations
df.isnull().sum() #gives null values of each sum


C1    0
C2    0
C3    0
C4    0
dtype: int64

In [84]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row 1","Row 2"],columns=["Columns1","Columns2","Columns3"])

In [78]:
df

Column1  Columns2  Columns3
Row 1        1       NaN         2
Row 2        1       3.0         4

In [81]:
df.isnull().sum()

Column1     0
Columns2    1
Columns3    0
dtype: int64

In [85]:
df['Columns2'].unique()

array([nan,  3.])

In [86]:
df>2

Columns1  Columns2  Columns3
Row 1     False     False     False
Row 2     False      True      True

In [88]:
df[df['Columns2']>2]

Columns1  Columns2  Columns3
Row 2         1       3.0         4

In [92]:
#reading files
df=pd.read_csv("DATA_STORAGE/loan_small.csv")
print(df)
df.head()

     Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002     NaN           5849.0                0.0         NaN  urban   
1   LP001003    Male           4583.0                NaN       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0    NaN   
3   LP001006  Female           2583.0             2358.0       120.0   semi   
4   LP001008    Male              NaN                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         NaN  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             18

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0  LP001002     NaN           5849.0                0.0         NaN  urban   
1  LP001003    Male           4583.0                NaN       128.0   semi   
2  LP001005    Male           3000.0                0.0        66.0    NaN   
3  LP001006  Female           2583.0             2358.0       120.0   semi   
4  LP001008    Male              NaN                0.0       141.0  urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3         NaN  
4           Y

In [93]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')
print(type(data))

<class 'str'>


In [94]:
from io import StringIO
#in memory file format object
StringIO(data)

In [95]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [97]:
pd.read_csv(StringIO(data),usecols=['col1','col2']) #now we get only col1 and col2

col1 col2
0    x    y
1    a    b
2    c    d

In [98]:
#converting to csv file
df.to_csv("sample.csv")

In [100]:
#datatypes in csv
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11')
pd.read_csv(StringIO(data))

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [107]:
df.isnull().sum()

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64

In [108]:
df.dtypes

Loan_ID               object
Gender                object
ApplicantIncome      float64
CoapplicantIncome    float64
LoanAmount           float64
Area                  object
Loan_Status           object
dtype: object